mutation createUnit($id: String!, $title: String!, $body: String, $schema: String, $answerable: Boolean) {
  createUnit(title: $title, courseId: $id, body: $body, schema: $schema, answerable: $answerable) {
    id
    title
    body
    schema
    answerable
  }
}
