query loadCourse($id: [String]) {
  courses(ids: $id) {
    id
    title
    schema
    units {
      id
      title
    }
    users {
      id
      email
      role
      profile {
        displayName
      }
    }
  }
}
