query marks($ids: [String], $userIds: [String]) {
  courses(ids: $ids) {
    id
    title
    users(ids: $userIds) {
      id
      email
      isAdmin
      role
      profile {
        displayName
      }
    }
    units {
      id
      title
      answerable
      answers(userIds: $userIds) {
        id
        updatedAt
        user {
          id
          email
        }
        marks {
          id
          mark
          createdAt
        }
      }
    }
  }
}
