query courses($idCourse: [String], $idUnit: [String], $idUser: [String]) {
  courses(ids: $idCourse) {
    id
    title
    users {
      id
      role
      profile {
        displayName
      }
    }
    units(ids: $idUnit) {
      id
      title
      body
      schema
      answerable
      weight
      answers(userIds: $idUser) {
        createdAt
        user {
          profile {
            displayName
          }
        }
        marks {
          id
          mark
          comment
          createdAt
        }
      }
    }
  }
  courseRole: courses(ids: $idCourse) {
    users(ids: $idUser) {
      role
    }
  }
}
